[package]
name = "retro_c8"
version = "2023.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
swift-bridge-build = "0.1"

[dependencies]
minifb = "0.25.0"
rand = "0.8.5"
swift-bridge = "0.1"
